# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 207a283b8e0d88f682c1d0c633f3dcae6cb3053e8064ac6a307c901ae09289e1872330863a69249c0b3d9a66f9e71f82f9ae0328874d46d18b6260f24ced2a85

test:
  secret_key_base: 5fcb81822bbbf0ef45afbd8514a976e1b457a9987ced7beb9de242d8b4d315d1d5c8aafac799fe04f0e772ef4f193f7b980d8c7985e4b68e512f96d58bb55096

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
